name : CI

on :
  push :
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps :
      - name: Checkout le repo
        uses: action/checkout@v4

      - name : Installer Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name : Installer les d√©pendances
        run: npm install

      - name: Lancer les tests
        run: npm test
